CONSOLE_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

LTO_ENABLE = yes
TAP_DANCE_ENABLE = no # 1200 bytes
MOUSEKEY_ENABLE = no # 1400 bytes
EXTRAKEY_ENABLE = yes # 440 bytes
COMBO_ENABLE = no # 952
KEY_OVERRIDE_ENABLE = no
WPM_ENABLE = no # 650 bytes
OLED_ENABLE = yes
ENCODER_MAP_ENABLE = yes # 744
QMK_SETTINGS = no # 3602 bytes

RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = no
