CONSOLE_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
OLED_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = no
QMK_SETTINGS = no

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = yes