CONSOLE_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

LTO_ENABLE = yes
TAP_DANCE_ENABLE = no # 1200 bytes
MOUSEKEY_ENABLE = no # 1400 bytes
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
WPM_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
QMK_SETTINGS = no

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = no
