VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

RGBLIGHT_ENABLE     = yes

OLED_ENABLE         = no
OLED_DRIVER         = SSD1306

EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
MOUSEKEY_ENABLE     = yes
COMBO_ENABLE        = yes
TAP_DANCE_ENABLE    = yes
KEY_OVERRIDE_ENABLE = no

QMK_SETTINGS        = no