VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

RGBLIGHT_ENABLE     = yes

OLED_ENABLE         = yes
OLED_DRIVER         = ssd1306

EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
MOUSEKEY_ENABLE     = no
COMBO_ENABLE        = no
TAP_DANCE_ENABLE    = no
KEY_OVERRIDE_ENABLE = no

QMK_SETTINGS        = no