VIA_ENABLE=yes
VIAL_ENABLE=yes
VIAL_INSECURE=yes

ENCODER_MAP_ENABLE=yes
VIALRGB_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306

QUANTUM_PAINTER_ENABLE = no
QUANTUM_PAINTER_DRIVERS += st7735_spi